// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package reflection

import (
	flatbuffers "github.com/tsingson/goflatbuffers/go"
)

type RPCCallT struct {
	Name          string
	Request       *ObjectT
	Response      *ObjectT
	Attributes    []*KeyValueT
	Documentation []string
}

// RPCCallT object pack function
func (t *RPCCallT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	nameOffset := flatbuffers.UOffsetT(0)
	if len(t.Name) > 0 {
		nameOffset = builder.CreateString(t.Name)
	}
	requestOffset := t.Request.Pack(builder)
	responseOffset := t.Response.Pack(builder)
	attributesOffset := flatbuffers.UOffsetT(0)
	if t.Attributes != nil {
		attributesLength := len(t.Attributes)
		attributesOffsets := make([]flatbuffers.UOffsetT, attributesLength)
		for j := attributesLength - 1; j >= 0; j-- {
			attributesOffsets[j] = t.Attributes[j].Pack(builder)
		}
		RPCCallStartAttributesVector(builder, attributesLength)
		for j := attributesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(attributesOffsets[j])
		}
		attributesOffset = RPCCallEndAttributesVector(builder, attributesLength)
	}
	documentationOffset := flatbuffers.UOffsetT(0)
	if t.Documentation != nil {
		documentationOffset = builder.StringsVector(t.Documentation...)
	}

	// pack process all field

	RPCCallStart(builder)
	RPCCallAddName(builder, nameOffset)
	RPCCallAddRequest(builder, requestOffset)
	RPCCallAddResponse(builder, responseOffset)
	RPCCallAddAttributes(builder, attributesOffset)
	RPCCallAddDocumentation(builder, documentationOffset)
	return RPCCallEnd(builder)
}

// RPCCallT object unpack function
func (rcv *RPCCall) UnPackTo(t *RPCCallT) {
	t.Name = string(rcv.Name())
	t.Request = rcv.Request(nil).UnPack()
	t.Response = rcv.Response(nil).UnPack()
	attributesLength := rcv.AttributesLength()
	t.Attributes = make([]*KeyValueT, attributesLength)
	for j := 0; j < attributesLength; j++ {
		x := KeyValue{}
		rcv.Attributes(&x, j)
		t.Attributes[j] = x.UnPack()
	}
	documentationLength := rcv.DocumentationLength()
	t.Documentation = make([]string, documentationLength)
	for j := 0; j < documentationLength; j++ {
		t.Documentation[j] = string(rcv.Documentation(j))
	}
}

func (rcv *RPCCall) UnPack() *RPCCallT {
	if rcv == nil {
		return nil
	}
	t := &RPCCallT{}
	rcv.UnPackTo(t)
	return t
}

type RPCCall struct {
	_tab flatbuffers.Table
}

// GetRootAsRPCCall shortcut to access root table
func GetRootAsRPCCall(buf []byte, offset flatbuffers.UOffsetT) *RPCCall {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RPCCall{}
	x.Init(buf, n+offset)
	return x
}

// GetTableVectorAsRPCCall shortcut to access table in vector of  unions
func GetTableVectorAsRPCCall(table *flatbuffers.Table) *RPCCall {
	n := flatbuffers.GetUOffsetT(table.Bytes[table.Pos:])
	x := &RPCCall{}
	x.Init(table.Bytes, n+table.Pos)
	return x
}

// GetTableAsRPCCall shortcut to access table in single union field
func GetTableAsRPCCall(table *flatbuffers.Table) *RPCCall {
	x := &RPCCall{}
	x.Init(table.Bytes, table.Pos)
	return x
}

func (rcv *RPCCall) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RPCCall) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RPCCall) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RPCCall) Request(obj *Object) *Object {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Object)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *RPCCall) Response(obj *Object) *Object {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Object)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *RPCCall) Attributes(obj *KeyValue, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RPCCall) AttributesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RPCCall) Documentation(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *RPCCall) DocumentationLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RPCCallStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}

func RPCCallAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}

func RPCCallAddRequest(builder *flatbuffers.Builder, request flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(request), 0)
}

func RPCCallAddResponse(builder *flatbuffers.Builder, response flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(response), 0)
}

func RPCCallAddAttributes(builder *flatbuffers.Builder, attributes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(attributes), 0)
}

func RPCCallStartAttributesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}

func RPCCallEndAttributesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.EndVector(numElems)
}

func RPCCallAddDocumentation(builder *flatbuffers.Builder, documentation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(documentation), 0)
}

func RPCCallStartDocumentationVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}

func RPCCallEndDocumentationVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.EndVector(numElems)
}

func RPCCallEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
