// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package types

import "strconv"

type BitWidth int8

const (
	BitWidthWIDTH_8  BitWidth = 0
	BitWidthWIDTH_16 BitWidth = 1
	BitWidthWIDTH_32 BitWidth = 2
	BitWidthWIDTH_64 BitWidth = 3

	BitWidthVerifyValueMin BitWidth = 0
	BitWidthVerifyValueMax BitWidth = 3
)

var EnumNamesBitWidth = map[BitWidth]string{
	BitWidthWIDTH_8:  "WIDTH_8",
	BitWidthWIDTH_16: "WIDTH_16",
	BitWidthWIDTH_32: "WIDTH_32",
	BitWidthWIDTH_64: "WIDTH_64",
}

var EnumValuesBitWidth = map[string]BitWidth{
	"WIDTH_8":  BitWidthWIDTH_8,
	"WIDTH_16": BitWidthWIDTH_16,
	"WIDTH_32": BitWidthWIDTH_32,
	"WIDTH_64": BitWidthWIDTH_64,
}

func (v BitWidth) String() string {
	if s, ok := EnumNamesBitWidth[v]; ok {
		return s
	}
	return "BitWidth(" + strconv.FormatInt(int64(v), 10) + ")"
}
