// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package reflection

import (
	flatbuffers "github.com/tsingson/goflatbuffers/go"
)

type EnumT struct {
	Name           string
	Values         []*EnumValT
	IsUnion        bool
	UnderlyingType *TypeT
	Attributes     []*KeyValueT
	Documentation  []string
}

// EnumT object pack function
func (t *EnumT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	nameOffset := flatbuffers.UOffsetT(0)
	if len(t.Name) > 0 {
		nameOffset = builder.CreateString(t.Name)
	}
	valuesOffset := flatbuffers.UOffsetT(0)
	if t.Values != nil {
		valuesLength := len(t.Values)
		valuesOffsets := make([]flatbuffers.UOffsetT, valuesLength)
		for j := valuesLength - 1; j >= 0; j-- {
			valuesOffsets[j] = t.Values[j].Pack(builder)
		}
		EnumStartValuesVector(builder, valuesLength)
		for j := valuesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(valuesOffsets[j])
		}
		valuesOffset = EnumEndValuesVector(builder, valuesLength)
	}
	underlyingTypeOffset := t.UnderlyingType.Pack(builder)
	attributesOffset := flatbuffers.UOffsetT(0)
	if t.Attributes != nil {
		attributesLength := len(t.Attributes)
		attributesOffsets := make([]flatbuffers.UOffsetT, attributesLength)
		for j := attributesLength - 1; j >= 0; j-- {
			attributesOffsets[j] = t.Attributes[j].Pack(builder)
		}
		EnumStartAttributesVector(builder, attributesLength)
		for j := attributesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(attributesOffsets[j])
		}
		attributesOffset = EnumEndAttributesVector(builder, attributesLength)
	}
	documentationOffset := flatbuffers.UOffsetT(0)
	if t.Documentation != nil {
		documentationOffset = builder.StringsVector(t.Documentation...)
	}

	// pack process all field

	EnumStart(builder)
	EnumAddName(builder, nameOffset)
	EnumAddValues(builder, valuesOffset)
	EnumAddIsUnion(builder, t.IsUnion)
	EnumAddUnderlyingType(builder, underlyingTypeOffset)
	EnumAddAttributes(builder, attributesOffset)
	EnumAddDocumentation(builder, documentationOffset)
	return EnumEnd(builder)
}

// EnumT object unpack function
func (rcv *Enum) UnPackTo(t *EnumT) {
	t.Name = string(rcv.Name())
	valuesLength := rcv.ValuesLength()
	t.Values = make([]*EnumValT, valuesLength)
	for j := 0; j < valuesLength; j++ {
		x := EnumVal{}
		rcv.Values(&x, j)
		t.Values[j] = x.UnPack()
	}
	t.IsUnion = rcv.IsUnion()
	t.UnderlyingType = rcv.UnderlyingType(nil).UnPack()
	attributesLength := rcv.AttributesLength()
	t.Attributes = make([]*KeyValueT, attributesLength)
	for j := 0; j < attributesLength; j++ {
		x := KeyValue{}
		rcv.Attributes(&x, j)
		t.Attributes[j] = x.UnPack()
	}
	documentationLength := rcv.DocumentationLength()
	t.Documentation = make([]string, documentationLength)
	for j := 0; j < documentationLength; j++ {
		t.Documentation[j] = string(rcv.Documentation(j))
	}
}

func (rcv *Enum) UnPack() *EnumT {
	if rcv == nil {
		return nil
	}
	t := &EnumT{}
	rcv.UnPackTo(t)
	return t
}

type Enum struct {
	_tab flatbuffers.Table
}

// GetRootAsEnum shortcut to access root table
func GetRootAsEnum(buf []byte, offset flatbuffers.UOffsetT) *Enum {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Enum{}
	x.Init(buf, n+offset)
	return x
}

// GetTableVectorAsEnum shortcut to access table in vector of  unions
func GetTableVectorAsEnum(table *flatbuffers.Table) *Enum {
	n := flatbuffers.GetUOffsetT(table.Bytes[table.Pos:])
	x := &Enum{}
	x.Init(table.Bytes, n+table.Pos)
	return x
}

// GetTableAsEnum shortcut to access table in single union field
func GetTableAsEnum(table *flatbuffers.Table) *Enum {
	x := &Enum{}
	x.Init(table.Bytes, table.Pos)
	return x
}

func (rcv *Enum) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Enum) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Enum) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Enum) Values(obj *EnumVal, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Enum) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Enum) IsUnion() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Enum) UnderlyingType(obj *Type) *Type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Type)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Enum) Attributes(obj *KeyValue, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Enum) AttributesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Enum) Documentation(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *Enum) DocumentationLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func EnumStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}

func EnumAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}

func EnumAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(values), 0)
}

func EnumStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}

func EnumEndValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.EndVector(numElems)
}

func EnumAddIsUnion(builder *flatbuffers.Builder, isUnion bool) {
	builder.PrependBoolSlot(2, isUnion, false)
}

func EnumAddUnderlyingType(builder *flatbuffers.Builder, underlyingType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(underlyingType), 0)
}

func EnumAddAttributes(builder *flatbuffers.Builder, attributes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(attributes), 0)
}

func EnumStartAttributesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}

func EnumEndAttributesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.EndVector(numElems)
}

func EnumAddDocumentation(builder *flatbuffers.Builder, documentation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(documentation), 0)
}

func EnumStartDocumentationVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}

func EnumEndDocumentationVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.EndVector(numElems)
}

func EnumEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
